version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
      PATH: /usr/lib/jvm/java-17-openjdk/bin/:${PATH}

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Set up JDK
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk/bin/java

      - run:
          name: Verify JDK Version
          command: java -version

      - run:
          name: Grant execute permission for Gradle wrapper
          command: chmod +x ./gradlew

      - run:
          name: Build with Gradle and Sign APK
          command: ./gradlew assembleRelease

      - run:
          name: Verify APK Path
          command: ls -R app/build/outputs/apk/release

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

  deploy:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Download build artifacts
          command: cp /mnt/circleci/app/build/outputs/apk/release/app-release.apk ./app-release.apk

      - run:
          name: Verify Downloaded APK Path
          command: ls -R ./app-release.apk

      - run:
          name: Debug Secrets (to be removed later)
          command: |
            echo "App ID: ${FIREBASE_APP_ID}"
            echo "Service Credentials: ${FIREBASE_CREDENTIAL_FILE_CONTENT}"
            echo "Release APK Path: ./app-release.apk"

      - run:
          name: Set up Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

      - run:
          name: Deploy to Firebase App Distribution
          command: |
            echo ${FIRE
